# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HabitatMap is an environmental tech org and maker of AirBeam
description: >- # this means to ignore newlines until "baseurl:"
  HabitatMap's AirBeam and AirCasting tools empower people to measure air pollution
  and advocate for equitable solutions to environmental health issues.
baseurl: "" # the subpath of your site, e.g. /blog
url: habitatmap.lunarlogic.io # the base hostname & protocol for your site
produrl: https://habitatmap.lunarlogic.io

plugins:
  - jekyll-feed
  - jekyll-import

# Search plugin config
algolia:
  application_id: BT6BD4TUL1
  index_name: habitatmap_dev

collections:
  posts:
    output: true
    permalink: /blog/:title
  categories:
    output: true
    permalink: /blog/categories/:name
  tags:
    output: true
    permalink: /blog/tags/:name
  faq:
    output: true
    permalink: /faq/:name
  faq_categories:
    output: true
  slides:
    output: true

defaults:
  -
    scope:
      type: posts
    values:
      author: Michael Heimbinder
      section: blog
  -
    scope:
      type: categories
    values:
      layout: category
      section: blog
  -
    scope:
      type: tags
    values:
      layout: tag
      section: blog
  -
    scope:
      type: faq
    values:
      layout: faq
      section: faq
  -
    scope:
      type: slides
    values:
      featured: false

algolia:
  application_id: BT6BD4TUL1
  index_name: habitatmap_dev
  # Exclude files from indexing
  files_to_exclude:
    - _slides/*
    - _faq_categories/*


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
