[[redirects]]
from = "/about_us"
to = "/about"
status = 301
force = false

[[redirects]]
from = "/markers"
to = "https://aircasting.org"
status = 301
force = false

[[redirects]]
from = "/markers/*"
to = "https://aircasting.org"
status = 301
force = false

[[redirects]]
from = "/forums"
to = "/"
status = 301
force = false

[[redirects]]
from = "/forums/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/topics/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/profiles"
to = "/"
status = 301
force = false

[[redirects]]
from = "/profiles/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/signup"
to = "/"
status = 301
force = false

[[redirects]]
from = "/sessions/forgot_password"
to = "/"
status = 301
force = false

[[redirects]]
from = "/habitatmap_docs/MakeYourOwnAirCastingLuminescentApparel.pdf"
to = "/assets/MakeYourOwnAirCastingLuminescentApparel.pdf"
status = 301
force = false

[[redirects]]
from = "/habitatmap_docs/HowToBuildAnAirCastingAirMonitor.pdf"
to = "/assets/HowToBuildAnAirCastingAirMonitor.pdf"
status = 301
force = false
