[[redirects]]
from = "/about_us"
to = "/about"
status = 302
force = false

[[redirects]]
from = "/markers"
to = "http://aircasting.org/map"
status = 302
force = false

[[redirects]]
from = "/markers/*"
to = "http://aircasting.org/map"
status = 302
force = false

[[redirects]]
from = "/forums"
to = "/"
status = 302
force = false

[[redirects]]
from = "/forums/*"
to = "/"
status = 302
force = false

[[redirects]]
from = "/topics/*"
to = "/"
status = 302
force = false

[[redirects]]
from = "/profiles"
to = "/"
status = 302
force = false

[[redirects]]
from = "/profiles/*"
to = "/"
status = 302
force = false

[[redirects]]
from = "/signup"
to = "/"
status = 302
force = false

[[redirects]]
from = "/sessions/forgot_password"
to = "/"
status = 302
force = false
