[[redirects]]
from = "/about_us"
to = "/about"
status = 301
force = false

[[redirects]]
from = "/markers"
to = "http://aircasting.habitatmap.org/map"
status = 301
force = false

[[redirects]]
from = "/markers/*"
to = "http://aircasting.habitatmap.org/map"
status = 301
force = false

[[redirects]]
from = "/forums"
to = "/"
status = 301
force = false

[[redirects]]
from = "/forums/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/topics/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/profiles"
to = "/"
status = 301
force = false

[[redirects]]
from = "/profiles/*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/signup"
to = "/"
status = 301
force = false

[[redirects]]
from = "/sessions/forgot_password"
to = "/"
status = 301
force = false

[[redirects]]
from = "/habitatmap_docs/MakeYourOwnAirCastingLuminescentApparel.pdf"
to = "https://content.instructables.com/FUH/F976/HAQ3BZA9/FUHF976HAQ3BZA9.pdf"
status = 301
force = false

[[redirects]]
from = "/habitatmap_docs/HowToBuildAnAirCastingAirMonitor.pdf"
to = "/assets/HowToBuildAnAirCastingAirMonitor.pdf"
status = 301
force = false
