---
layout: post
title: AirCasting from Williamsburg, Brooklyn
date: 2012-12-21 12:50:35.000000000 +01:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories: []
tags: []
meta:
  _edit_last: '1'
  _wp_old_slug: '291'
permalink: "/aircasting-from-williamsburg-brooklyn/"
---
<p>Mayeta Clark, an intern at the New York Times video desk, contacted me a few months back to discuss AirCasting. I suggested that rather than do a sit-down interview, she capture AirCasting in action, because context is everything, right?  If the air is always safe to breathe where you live then personal air quality monitoring isn’t particularly relevant. But it’s a different story when the air is frequently foul, as it is in some areas surrounding Newtown Creek in North Brooklyn. So after agreeing to a location shoot that’s where we headed.</p>
<p>I like watching the sunset behind the Manhattan skyline so I charted a route for us between two of my favorite Williamsburg sunset spots: the Scott Ave. pedestrian overpass and Grand Ferry Park. Both spots also happen to be located next to facilities that pollute the air. <a href="http://habitatmap.org/markers/125-allocco-recycling-scholes-st" target="_blank">Allocco</a> runs a busy construction and demolition debris waste transfer station on Scott Ave. and the <a href="http://habitatmap.org/markers/225-n-1st-st-power-plant">New York Power Authority</a> operates a peaker power plant on the waterfront parcel adjacent to Grand Ferry Park.</p>
<p>[caption id="Bike+AirCastingAirMonitors" align="aligncenter" width="600" caption="Ready to roll! The CO+NO2+T+RH AirCasting Air Monitor in white and the PM monitor in grey."]<img title="Bike+AirCastingAirMonitors" src="{{ site.baseurl }}/assets/Bike+AirCastingAirMonitors.jpg" alt="SThe CO+NO2+T+RH AirCasting Air Monitor in white and the PM monitor in grey. Both are attached to my backpack using carbiners and velcro straps" width="600" height="335" />[/caption]</p>
<p>&nbsp;</p>
<p>[caption id="ScottPedestrianBridgeView" align="aligncenter" width="600" caption="Looking west towards Manhattan from the pedestrian overpass. Allocco can be seen in the foreground."]<img title="ScottPedestrianBridgeView" src="{{ site.baseurl }}/assets/ScottPedestrianBridgeView.jpg" alt="Looking west towards Manhattan from the Scott Ave. pedestrian overpass.  Allocco's facility can be seen in the foreground." width="600" height="305" />[/caption]</p>
<p>&nbsp;</p>
<p>[caption id="Allocco" align="aligncenter" width="600" caption="An Allocco employee closing the gate to keep out prying eyes. Allocco is one of the &quot;better&quot; waste transfer stations in the area. Their Kingsland Ave. station exports material by barge, keeping trucks off the road."]<img title="Allocco" src="{{ site.baseurl }}/assets/Allocco.jpg" alt="An Allocco employee closing the gate to keep out prying eyes.  Allocco is one of the " width="600" height="315" />[/caption]</p>
<p>&nbsp;</p>
<p>While both these facilities contribute to poor air quality in the surrounding neighborhoods, the worst offenders are the thousands of diesel trucks that ply local roadways and the BQE.  <a href="http://www.takingspace.org/aircasting-in-action/" target="_blank">As I’ve written previously</a>, the section of East Williamsburg we traversed is plagued by a seemingly endless procession of trucks making their way up and down Grand St., Metropolitan Ave., and Vandervoort Ave. According to a <a href="http://www.newtowncreekalliance.org/docs/OUTRAGE_TruckTraffic&amp;AirQualityReportSummary.pdf" target="_blank">Truck Study</a> conducted by Organizations United for Trash Reduction and Garbage Equity, half these trucks are carrying waste. Not a surprise when you know this area handles nearly 40% of the 12 million plus tons of waste moving through <a href="http://www.newtowncreekalliance.org/waste-transfer-stations/" target="_blank">waste transfer stations in New York City</a> annually.</p>
<p>[caption id="MetropolitanAve" align="aligncenter" width="600" caption="The industrial section of Metropolitan Ave. east of the Grand St. Bridge"]<img title="MetropolitanAve" src="{{ site.baseurl }}/assets/MetropolitanAve.jpg" alt="The industrial section of Metropolitan Ave east of the Grand St. Bridge" width="600" height="267" />[/caption]</p>
<p>&nbsp;</p>
<p>[caption id="Trucks+HomesOnMetropolitan" align="aligncenter" width="600" caption="West of the Grand St. Bridge Metropolitan Ave. is lined with 2 and 3 story homes. The exhaust and noise from the nearly constant truck traffic takes it toll on East Williamsburg residents."]<img title="Trucks+HomesOnMetropolitan" src="{{ site.baseurl }}/assets/Trucks+HomesOnMetropolitan.jpg" alt="West of the Grand St. Bridge Metropolitan Ave. is lined with 2 and 3 story homes. The exhaust and noise from the nearly constant truck traffic takes it toll on East Williamsburg residents" width="600" height="295" />[/caption]</p>
<p>&nbsp;</p>
<p>Unfortunately, I ran into some difficulties AirCasting the route I had selected. On the first attempt, with Mayeta accompanying, we ran out of time. During the second attempt my phone battery died. And on the third attempt my phone crashed. Aaaargh!  So on my fourth go, I decided to forgo stopping to attach photos and notes to my session or walk at a stable pace and just hopped on my bike and rode. Then of course it started to rain! but fortunately the rain didn’t last long.</p>
<p>The <a href="http://www.aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':100,'high':75,'mid':50,'low':25,'lowest':0},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'CO%20Gas-TGS2442'}&amp;map={'zoom':15,'lat':40.71343391137626,'lng':-73.94533250500001,'mapType':'hybrid'}" target="_blank">carbon monoxide</a> (CO) measurements didn’t budge for the entire session and the <a href="http://www.aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':100,'high':75,'mid':50,'low':25,'lowest':0},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'N02%20Gas-MiCS-2710'}&amp;map={'zoom':15,'lat':40.71343391137626,'lng':-73.94533250500001,'mapType':'hybrid'}" target="_blank">nitrogen dioxide</a> (NO2) measurements were also mostly stable. (When viewing the sessions, toggle the arrow on the bottom left to view the graph; hover your mouse over the graph to see the corresponding location on the map). I believe the measurements are stable because the gas sensors we’re using don’t provide high enough resolution to detect part per billion or even part per million changes in gas concentrations.</p>
<p>To address this shortcoming we have two projects underway. First, we’re working with Michael Taylor from Carnegie Mellon to develop a sensor package that uses an electrochemical CO sensor rather than a metal-oxide one. These sensors are more expensive but we’re hoping the expense will be justified by a lower detection limit and higher resolution. Second, we’re working with the New York Hall of Science and the New York City College of Technology to develop a low-cost calibration lab. This will allow us to place the AirCasting Air Monitors in an exposure chamber and test their response to known gas concentrations.</p>
<p>The <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':100,'high':75,'mid':50,'low':25,'lowest':0},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'Particulate%20Matter-PPD42NS'}&amp;map={'zoom':15,'lat':40.71262092056129,'lng':-73.93258664776124,'mapType':'hybrid'}" target="_blank">particulate matter</a> (PM) measurements are difficult to interpret because the data stream is very noisy, with measurements jumping up and down a lot. This sensor counts particles as they flow through a chamber and interrupt a tightly focused LED light beam. Normally, a sensor of this design would record measurements every second but display data in one minute increments or greater to average out the noise. However, when you’re walking, or riding a bike like I was, the spatial resolution provided by one minute readings is insufficient to identify sources. (I could be blocks away by the time a reading is displayed and never know where exactly my highest measurements were recorded).</p>
<p>To make sense of the noisy PM measurements, AirCasting provides average measurement values for defined areas via the <a href="http://aircasting.org/map#/map_crowd?data={'location':{},'gridResolution':25,'tags':','usernames':','sensorId':'Particulate%20Matter-PPD42NS','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':20,'high':15,'mid':10,'low':5,'lowest':0}}&amp;map={'zoom':14,'lat':40.71333632420424,'lng':-73.9389381187085,'mapType':'hybrid'}" target="_blank">CrowdMap</a>.  But rather than average together measurements from a single stationary monitor, the CrowdMap averages together measurements from multiple monitors, carried by multiple AirCasters, during multiple AirCasting sessions. We believe this approach will compliment stationary air monitoring networks by increasing the spatial resolution of air quality data, helping to identify hot spots and sources, while also providing a better assessment of personal exposure to air pollution.</p>
<p><a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':100,'high':75,'mid':50,'low':25,'lowest':0},'sensorId':'}&amp;sessionsIds=[1383]&amp;tmp={'tmpSensorId':'Particulate%20Matter-PPD42NS'}&amp;map={'zoom':18,'lat':40.712567918806634,'lng':-73.924006985,'mapType':'hybrid'}" target="_blank">On my first AirCasting attempt</a> the PM measurements were higher from the pedestrian bridge to the waste transfer station and declined as I walked towards Metropolitan Ave. <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':100,'high':75,'mid':50,'low':25,'lowest':0},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'Particulate%20Matter-PPD42NS'}&amp;map={'zoom':15,'lat':40.71262092056129,'lng':-73.93258664776124,'mapType':'hybrid'}" target="_blank">On my final attempt</a> I rode past the facility twice and each time the measurements were slightly elevated compared to the surrounding streets but not any higher than was generally the case as I cut west across Williamsburg picking my way towards the waterfront. One finding from this trip is that excessive shaking of the particle counter tends to falsely elevate the measurements. I attribute the spikes at the end of the session to taking off my backpack and dropping it down as I moved around the park. Michael Taylor is going to help us with this problem too, adding a fan to the exhaust port of the particle counter to regularize the air flow.</p>
<p>I also recorded <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':59,'high':56,'mid':53,'low':50,'lowest':47},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'Temperature-TMP36'}&amp;map={'zoom':15,'lat':40.71343391137626,'lng':-73.94533250500001,'mapType':'hybrid'}" target="_blank">temperature</a>, <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':74,'high':69,'mid':64,'low':59,'lowest':54},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'Humidity-HIH4030'}&amp;map={'zoom':15,'lat':40.71369414313647,'lng':-73.9466628806714,'mapType':'hybrid'}" target="_blank">relative humidity</a>, and <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2012},'heat':{'highest':130,'high':120,'mid':110,'low':100,'lowest':90},'sensorId':'}&amp;sessionsIds=[1402]&amp;tmp={'tmpSensorId':'Heart%20Rate-Zephyr%20HxM'}&amp;map={'zoom':15,'lat':40.713820468446244,'lng':-73.94013909334718,'mapType':'hybrid'}" target="_blank">heart rate</a>. Have a look if you’re curious. You can see when it started and stopped raining by looking at the RH stream and noting when I stopped and took cover under awnings.</p>
