---
layout: post
title: Greenpeace Poison Gas Disaster Map!
date: 2012-02-03 10:52:34.000000000 +01:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories: []
tags: []
meta:
  _edit_last: '1'
permalink: "/greenpeace-poison-gas-disaster-map/"
---
<p>This <a href="http://usactions.greenpeace.org/chemicals/map/" target="_blank">scary map from Greenpeace</a> maps U.S. chemical plants and their potential poison gas cloud fallout zones.  Like the EPA greenhouse gas map I blogged about a few weeks back, the Houston Ship Channel area has the densest concentration of facilities followed by the "chemical corridor" between Baton Rouge and New Orleans.  It would be great if this map was bigger and the facilities list generated by address searches generated a complete rather than a partial list of facilities.  There should also be a way to toggle off the fallout zones because they obscure the underlying map.</p>
<p>But mostly what this maps needs is a better explanation.  I'd like to know what types of chemicals pose the greatest threat and I'd like to know how often these types of accidents have happened in the U.S.  Growing up in Houston I remember hearing about an <a href="http://blog.chron.com/bayoucityhistory/2011/05/35-years-later-houstons-deadly-ammonia-truck-disaster/" target="_blank">ammonia tanker truck that crashed</a> at the intersection of the Southwest Freeway and the West Loop releasing a toxic cloud that killed seven people and led to the hospitalization of seventy-eight.</p>
<p>[caption id="" align="alignnone" width="600" caption="That white cloud in the distance is the toxic blanket of anhydrous ammonia fumes. (Texas Air Control Board/Houston Post file)"]<img src="{{ site.baseurl }}/assets/Ammonia9-600x458.jpg" alt="" width="600" height="458" />[/caption]</p>
<p>Clicking through the markers, I see lots of chlorine plants.  What is all this chlorine for, people's pools?  According to the law firm <a href="http://www.williamsbailey.com/articles/chlorine-gas-refinery-injuries/" target="_blank">Williams Kherker</a>, which represents chlorine gas refinery workers who have been injured on the job, "Chlorine is commonly used in cleaning and sanitation efforts. It is found in drinking water and swimming pools, as well as being used in industrial settings such as oil refineries. Sulfur used in the oil refinement process creates a large amount of pollution, which is reduced when chlorine is added into the sulfur emissions."</p>
