---
layout: post
title: 'Air Quality Scientist Goes AirCasting (Part 2): Smokers Beware!'
date: 2013-11-12 19:59:00.000000000 +01:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories: []
tags: []
meta:
  _edit_last: '1'
author: Matt Harper
permalink: "/air-quality-scientist-goes-aircasting-part-2-smokers-beware/"
---
<p>Last week, <a href="http://www.takingspace.org/air-quality-scientist-goes-aircasting-part-1/">I wrote about Aircasting with my Car-Neph</a>. This week, I want to tell you about my Backpack-Neph.</p>
<p>[caption id="" align="alignnone" width="600" caption="The Backpack-Neph"]<img style="text-decoration: underline;" title="The Backpack-Neph" src="{{ site.baseurl }}/assets/BackpackNeph.jpg" alt="The Backpack-Neph" width="600" height="436" />[/caption]</p>
<p>The below image provides an overhead view of the <a href="http://www.pscleanair.org/" target="_blank">Puget Sound Clean Air Agency's</a> office building in downtown Seattle with my <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':'harpernavy1@gmail,%20','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2013},'heat':{'highest':100,'high':70,'mid':50,'low':30,'lowest':0},'sensorId':'}&amp;sessionsIds=[2642]&amp;tmp={'tmpSensorId':'Light%20Scatter-M903'}&amp;map={'zoom':18,'lat':47.61150987877286,'lng':-122.33840915562905,'mapType':'hybrid'}" target="_blank">AirCasting tracks and graph overlaid</a>. The day was blustery and cool, so there was little background air pollution outside (Green Air Quality Index). I turned on my Backpack-Neph, collected some indoor air, and then headed outside to the bus stop. There weren't many people there at the time but there were two buses. I brought my Backpack-Neph over to where the buses were and sampled some of that air. The first spike into the yellow on the graph is the bus exhaust. Next, I walked around the city some more before returning to the bus stop. When I showed up again there were several people smoking cigarettes next to two buses. The second spike, which reaches into the red, illustrates the impact the smokers were having on the air I was breathing. Yuck! Smokers beware, I'll be watching you with  my Backpack-Neph!</p>
<p>[caption id="" align="alignnone" width="600" caption="Taking the Backpack-Neph for a spin in downtown Seattle"]<a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':'harpernavy1@gmail,%20','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2013},'heat':{'highest':100,'high':70,'mid':50,'low':30,'lowest':0},'sensorId':'}&amp;sessionsIds=[2642]&amp;tmp={'tmpSensorId':'Light%20Scatter-M903'}&amp;map={'zoom':18,'lat':47.61150987877286,'lng':-122.33840915562905,'mapType':'hybrid'}" target="_blank"><img style="text-decoration: underline;" title="Taking the Backpack-Neph for a spin in downtown Seattle" src="{{ site.baseurl }}/assets/BackpackNephMap.jpg" alt="Taking the Backpack-Neph for a spin in downtown Seattle" width="600" height="478" /></a>[/caption]</p>
<p>Part of my job, and one of my passions, is communicating the complexities of air quality science in ways that are accessible to the public. To that end, all my <a href="http://aircasting.org/map#/map_sessions?data={'location':{'address':','distance':'10','limit':false},'gridResolution':25,'tags':','usernames':'harpernavy1@gmail,%20','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2013},'heat':{'highest':100,'high':80,'mid':70,'low':60,'lowest':20},'sensorId':'}&sessionsIds=[]&tmp={'tmpSensorId':'}&map={'zoom':9,'lat':47.49166085634124,'lng':-122.2906175554017,'mapType':'roadmap'}" target="_blank">AirCasting sessions</a> are public and have been contributed to the <a href="http://aircasting.org/map#/map_crowd?data={'location':{},'gridResolution':50,'tags':','usernames':'harpernavy1@gmail,%20','sensorId':'Light%20Scatter-M903','time':{'timeFrom':300,'timeTo':1739,'dayFrom':0,'dayTo':365,'yearFrom':2011,'yearTo':2013},'heat':{'highest':500,'high':226,'mid':144,'low':50,'lowest':0}}&amp;map={'zoom':9,'lat':47.3769672810007,'lng':-122.09514497292582,'mapType':'hybrid'}" target="_blank">CrowdMap</a>. To view my data, simply visit the AirCasting website and filter the sessions or CrowdMap using my profile name: harpernavy1@gmail.com.</p>
<p><em>Matt Harper has worked for the Puget Sound Clean Air Agency for 11 years and is currently the Air Monitoring Lead. He has a B.S. in Manufacturing Engineering from Boston University and an M.B.A. from the University of New Haven. He is also a Commander in the United States Navy Reserve, with 7 years of Active and 11 years of Reserve service as a Submarine Warfare Officer. He is interested in using sensing technology to help guide people to healthier daily behaviors.</em></p>
