backend:
  name: git-gateway
  # name: test-repo
  branch: press-page

media_folder: images/uploads

collections:
  - name: blog # Used in routes, e.g., /admin/collections/blog
    label: Blog # Used in the UI
    label_singular: Post # Used in the UI, ie: New Post
    folder: _posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Jekyll requires this format for blog posts
    fields: # The fields for each document, usually in front matter
      - { label: Layout, name: layout, widget: hidden, default: post }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - {
          label: Featured?,
          name: featured,
          widget: boolean,
          default: false,
          hint: "Make sure only one of your posts is marked as featured.
            Otherwise you won't know for sure which of the featured
            posts will show up on the main blog page.",
        }
      - {
          label: Author,
          name: author,
          widget: relation,
          collection: authors,
          displayFields: [display_name],
          searchFields: [display_name],
          valueField: display_name,
          required: false,
          hint: "If you don't set an author, it will be Michael Heimbinder.",
        }
      - {
          label: Image,
          name: image,
          widget: image,
          hint: "For the best effect upload images 1200x705 in resolution (or bigger with the same proportions).",
        }
      - { label: Intro, name: intro, widget: text, required: false }
      - {
          label: Body,
          name: body,
          widget: markdown,
          buttons:
            [
              bold,
              italic,
              code,
              link,
              heading-two,
              quote,
              code-block,
              bulleted-list,
              numbered-list,
            ],
        }
      - {
          label: Category,
          name: category,
          widget: relation,
          collection: categories,
          displayFields: [name],
          searchFields: [name],
          valueField: name,
        }
      - {
          label: Tags,
          name: tag,
          widget: relation,
          collection: tags,
          displayFields: [name],
          searchFields: [name],
          valueField: name,
          multiple: true,
        }

  - name: user_stories
    label: User stories
    label_singular: User story
    folder: _user_stories
    create: true
    slug: "{{title}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: user_story }
      - { label: Organization name, name: title, widget: string }
      - {
          label: Featured?,
          name: featured,
          widget: boolean,
          default: false,
          hint: "Make sure only 6 of your user stories are marked as featured.
            Otherwise you won't know for sure which of the featured
            user stories will show up in the slider.",
        }
      - {
          label: Image,
          name: image,
          widget: image,
          hint: "For the best effect upload images 1200x705 in resolution (or bigger with the same proportions).",
        }
      - { label: Intro, name: intro, widget: text, required: false }
      - {
          label: Body,
          name: body,
          widget: markdown,
          buttons:
            [
              bold,
              italic,
              code,
              link,
              heading-two,
              quote,
              code-block,
              bulleted-list,
              numbered-list,
            ],
        }
      - {
          label: Type,
          name: type,
          widget: select,
          options:
            [
              "Educators",
              "Citizen Scientists",
              "Researchers",
              "Activists & Non-profits",
            ],
        }
      - {
          label: Order,
          name: order,
          widget: number,
          valueType: int,
          min: 1,
          hint: "Specifies the order in which user stories will be displayed, both on the user stories index page and the slider.",
        }

  - name: testimonials
    label: Testimonials slider
    label_singular: Testimonial
    folder: _testimonials
    identifier_field: institution
    create: true
    editor:
      preview: false
    fields:
      - { label: Institution, name: institution, widget: string }
      - { label: Quote, name: quote, widget: string }
      - { label: Name, name: name, widget: string }

  - name: news_quotes
    label: News quotes slider
    label_singular: News quote
    folder: _news_quotes
    identifier_field: publication
    create: true
    editor:
      preview: false
    fields:
      - { label: Publication, name: publication, widget: string }
      - { label: Quote, name: quote, widget: string }
      - { label: link, name: link, widget: string }

  - name: authors
    label: Authors
    label_singular: Author
    folder: _authors
    identifier_field: name
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: Short Name, name: name, widget: string }
      - { label: Display Name, name: display_name, widget: string }

  - name: categories
    label: Categories
    label_singular: Category
    folder: _categories
    identifier_field: name
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Category name,
          name: name,
          widget: string,
          hint:
            "If you need to change the name of an existing category, please delete it and create a new one.
            If you edit an existing category, the link to the category blog page will break.",
        }

  - name: tags
    label: Tags
    label_singular: Tag
    folder: _tags
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - {
          label: Tag name,
          name: name,
          hint:
            "If you need to change the name of an existing tag, please delete it and create a new one.
            If you edit an existing tag, the link to the tag blog page will break.",
        }

  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: "_data/faq.yml"
        label: FAQ
        name: faq
        fields:
          - name: faq_items
            label: FAQ Items
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }
              - {
                  label: Category,
                  name: category,
                  widget: relation,
                  collection: faq_categories,
                  displayFields: [name],
                  searchFields: [name],
                  valueField: name,
                }

  - name: faq_categories
    label: FAQ categories
    label_singular: FAQ category
    folder: _faq_categories
    identifier_field: name
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Category name,
          name: name,
          widget: string,
          hint:
            "If you need to change the name of an existing category, please delete it and create a new one.
            If you edit an existing category, the link to the category blog page will break.",
        }
      - {
          label: Order,
          name: order,
          widget: number,
          valueType: int,
          min: 1,
          hint:
            "Specifies the order in which FAQ categorized groups will be displayed.
            Best to use 1 to X where X is the total count of FAQ categories to keep track.",
        }
